---
name: WWW-Shorten-isgd
version: 0.01
author:
  - Brandon Gilmore <brandon@mg2.org>
abstract: Perl interface to is.gd
license: perl
resources:
  license: http://dev.perl.org/licenses/
requires:
  WWW::Shorten: 1.97
build_requires:
  Test::More: 0
provides:
  WWW::Shorten::isgd:
    file: lib/WWW/Shorten/isgd.pm
    version: 0.01
generated_by: vim
